[package]

name = "gallium"
version = "0.0.1"
authors = ["Charlie Cummings <chc4000@gmail.com>"]

[dependencies.log]
log = "*"

[dependencies.xcb]
version = "^0.7"
features = ["xlib_xcb"]

[dependencies]
bitflags = "^0.1"
rustc-serialize = "0.3"
libc = "*"
x11 = "*"

[[bin]]
name = "gallium"
